### ISSUE TITLE
Extra Metadata Loader Save Videos in Custom Location

### ISSUE THREAD

**Issue by QuirkyKirkHax** [darklinkpower/PlayniteExtensionsCollection#378] opened 2023-03-03 00:51 UTC
### Extension name

Extra Metadata Loader

### Feature Description

It would be nice to be able to save our videos and stuff in a different location than inside of our appdata folder.  I have an SMB share where I keep my basic metadata stuff for Launchbox, and it would be cool to be able to host videos and stuff on there instead of on my local SSD if possible.

**Comment by darklinkpower** [comment] 2023-03-03 01:58
Duplicate of https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/109

**Closed by darklinkpower** 2023-03-03 01:58 UTC
Labels: enhancement, ExtraMetadataLoader
