### ISSUE TITLE
[PlayState] Crash with custom game action using steam://launch/ URI

### ISSUE THREAD

**Issue by CanRanBan** [darklinkpower/PlayniteExtensionsCollection#280] opened 2022-07-15 23:23 UTC
### Extension name

PlayState

### Bug Description

Starting any steam game using a custom game action leads to a crash of the PlayState extension.

It doesn't matter if the game itself offers a dialog on start or not.
Both the default URI (`steam://launch/ID/`) and a non-default URI (`steam://launch/ID/Option1`) result in an extension crash.

All other extensions except library extensions were disabled for the test.

### To Reproduce

Add a game action with `Link` type and enabled `Play action` checkbox using one of the two following URIs (with GTA V as an example game) leads to the mentioned crash:

- Default launch URI: `steam://launch/271590/`
- Non-default launch URI: `steam://launch/271590/Option1`

Confirmed the bug with a different game that doesn't offer other launch URIs using the default launch URI.

### Extensions log

Attached logs contain only the part between pressing Play and restarting Playnite with the extension crash dialog.
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/9124639/playnite.log)
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/9124640/extensions.log)

### Screenshots

![Screenshot 2022-07-16 010743](https://user-images.githubusercontent.com/24878047/179323011-c1aaab3e-c9ea-496e-bc35-e154aaaf47c3.png)
![Screenshot 2022-07-16 010751](https://user-images.githubusercontent.com/24878047/179323016-9b19803e-4830-4bf9-82cc-c4049002c889.png)
![Screenshot 2022-07-16 010323](https://user-images.githubusercontent.com/24878047/179323024-304bc333-e1d9-4334-8e4f-8f35cd98c92c.png)

**Comment by darklinkpower** [comment] 2022-07-16 02:29
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/0ea5daa13d8bc1e698cd165e79431f965c113a24

The core of the issue is that the plugin is being told twice that the game has started. I've opened an issue here https://github.com/JosefNemec/Playnite/issues/2988

**Closed by darklinkpower** 2022-07-16 02:29 UTC
Labels: bug
