### ISSUE TITLE
[NVIDIA GeForce NOW Enabler] Error when running "Update enabled status of games" function

### ISSUE THREAD

**Issue by pcmccollum** [darklinkpower/PlayniteExtensionsCollection#538] opened 2024-05-19 18:05 UTC
### Extension name

NVIDIA GeForce NOW Enabler

### Bug Description

When attempting to run the "Update enabled status of games" function, I receive the following error message:

```
Error converting value "INTERACTIVE_CONTENT" to type
'NVIDIAGeForceNowEnabler.Models.AppType'. Path 'data.apps.items[544].type',
line 1, position 196132.
```

After clicking "OK", I receive:

```
NVIDIA GeForce NOW enabled games in library: 211

Added "NVIDIA GeForce NOW" feature to 0 games.
Removed "NVIDIA GeForce NOW" feature from 0 games.

Marked 0 games as Installed.
```

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/15370310/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/15370316/playnite.log)

**Comment by darklinkpower** [comment] 2024-06-02 06:27
Duplicate of https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/537

**Closed by darklinkpower** 2024-06-02 06:27 UTC
Labels: bug, NVIDIAGeForceNowEnabler
