### ISSUE TITLE
[Display Helper] Resolution Doesn't Revert Back

### ISSUE THREAD

**Issue by XxRecKLesSxX** [darklinkpower/PlayniteExtensionsCollection#440] opened 2023-09-23 15:36 UTC
### Extension name

 Display Helper

### Bug Description

When I Choose a resolution for a game and click play it start in the chosen resolution  but when closed it doesn't revert back

### To Reproduce

It happens every time with every game

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12706784/extensions.log)

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12706785/playnite.log)

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/145856276/71015e81-6f33-464a-815b-af170c378a43)
 That's The Settings for me right now (Not Sure if it's Related  but when i change the settings to this 
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/145856276/30e855ac-a75e-49a5-bcdb-0c634a5dddde)

The Resolution for the game Doesn't Change even if i changed and it just stays the same resolution for my chosen display in the above sshot

**Comment by darklinkpower** [comment] 2023-09-23 19:12
Duplicate of #433

**Closed by darklinkpower** 2023-09-23 19:12 UTC
Labels: bug
