### ISSUE TITLE
[JAST USA Library] Only Some Games Detected

### ISSUE THREAD

**Issue by burnpsy** [darklinkpower/PlayniteExtensionsCollection#234] opened 2022-04-16 03:50 UTC
### Extension name

JAST USA Library

### Bug Description

I installed your new JAST USA addon and authenticated my JAST account. Said account has 75 games purchased. Only 20 were detected by a library update.

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8499207/extensions.log)

**Comment by darklinkpower** [comment] 2022-04-16 03:56
Sorry, it was caused by a line I used while debugging and forgot to delete for the release. Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/0f07af48f2cc614151a42cfd68ab3d7bb1ea8f3b

**Closed by darklinkpower** 2022-04-16 03:56 UTC
Labels: bug
