### ISSUE TITLE
[P9] [GamePassCatalogBrowser] Games list is empty, games are all in Collections list

### ISSUE THREAD

**Issue by Jeshibu** [darklinkpower/PlayniteExtensionsCollection#41] opened 2021-09-06 14:00 UTC
In the P9 beta, the xbox game pass catalog browser window starts up with "Games" selected in the Collections dropdown, which shows an empty list on the left. "EA Games" works as expected. "Collections" shows what "Games" probably should.

**Comment by Jeshibu** [comment] 2021-09-06 18:00
This went away when I got rid of the cache. Not sure where the cache went wrong.

[gamesCache.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7117376/gamesCache.zip)

**Comment by darklinkpower** [comment] 2022-03-14 06:00
Closing since it has not been reported and I couldn't reproduce it.

**Closed by darklinkpower** 2022-03-14 06:00 UTC
Labels: bug, GamePassCatalogBrowser
