### ISSUE TITLE
[Installation Status Updater] Playnite Crash

### ISSUE THREAD

**Issue by ImWoood** [darklinkpower/PlayniteExtensionsCollection#264] opened 2022-06-12 11:09 UTC
### Extension name

Installation Status Updater

### Bug Description

Playnite crashes randomly because of Installation Status Updater. Playnite crashes when it just runs in the background and when I'm playing a game. It crashes randomly no matter what I'm doing. I think the time it takes until Playnite crahes is random too. The Extension works, it just crashes Playnite.

### To Reproduce

I have no idea. It crashes randomly no matter what I'm doing.

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8885696/extensions.log)

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8886149/playnite.log)

### Screenshots

![image](https://user-images.githubusercontent.com/107350003/173231431-3a4b4fc8-3c3a-4f65-a10c-07ee797cecf6.png)

_No response_

**Comment by darklinkpower** [comment] 2022-06-12 13:44
Can you upload your Playnite.log file too please? There isn't any info regarding the crash in the extensions.log file but it should be in that other file

**Comment by darklinkpower** [comment] 2022-06-12 13:49
Also has this always happened, was it after an update?

**Comment by ImWoood** [comment] 2022-06-12 15:40
> Also has this always happened or was it after an update?

This happened already for few weeks. After I installed the extension everything worked but after a few weeks it began to crash. I hoped maybe this update would fix it but sadly it didn't.

**Comment by darklinkpower** [comment] 2022-06-12 19:19
It's the same issue as  #260 

Can you install the debug build, run the status check and upload your logs? https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/260#issuecomment-1152730702

**Comment by darklinkpower** [comment] 2022-06-18 20:10
I'm sorry, it seems I made a mistake and uploaded the incorrect build that didn't log all that I needed. Can you do the same thing with this one and upload the logs afterwards? Sorry for the inconvenience. I also added a small change that may fix the issue.

[Installation_Status_Updater_2_31.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8934273/Installation_Status_Updater_2_31.zip)

**Comment by ImWoood** [comment] 2022-06-18 22:14
> I'm sorry, it seems I made a mistake and uploaded the incorrect build that didn't log all that I needed. Can you do the same thing with this one and upload the logs afterwards? Sorry for the inconvenience. I also added a small change that may fix the issue.
> 
> [Installation_Status_Updater_2_31.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8934273/Installation_Status_Updater_2_31.zip)

Sry, I don't think I can help you find the bug anymore. I'm not sure why, but Playnite doesn't crash anymore. I don't know if it was because of a game I have uninstalled now or something else, but I don't have any problems with this Add-On anymore. Still, thank you for helping me. If it still helps somehow even if I don't have the bug anymore, here are my logs.

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8934433/extensions.log)

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8934434/playnite.log)

**Comment by darklinkpower** [comment] 2022-06-18 23:31
Thanks. Just as last info, this the issue disappear after installing this test version or was it before? I'm wondering if the fix attempt I made on it is what fixed it.

**Comment by ImWoood** [comment] 2022-06-18 23:43
I think the issue disappeared after I installed the 2.30 debug build.

**Comment by darklinkpower** [comment] 2022-06-19 00:27
oh I see, the issue is actually still there. The issue doesn't show anymore because the error is being catched and preventing from stopping execution. The latest log contains the info I needed to fix it, I'll look into it, thanks.

**Comment by ImWoood** [comment] 2022-06-19 00:53
np

**Comment by darklinkpower** [comment] 2022-06-19 00:56
I identified the issue. Your game `Azur Lane` has quote characters in the game action path `"C:\Program Files\BlueStacks_nxt\HD-Player.exe"` and causes the error. I'll do something to prevent the error.

**Comment by ImWoood** [comment] 2022-06-19 01:02
Oh, I forgot to remove the quotation marks when I copied the path.

**Comment by darklinkpower** [comment] 2022-06-19 03:04
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/bf1fc66c7c1c8c6ed7bb289b3c9e5021a03dead3

**Closed by darklinkpower** 2022-06-19 03:04 UTC
Labels: bug

**Comment by ImWoood** [comment] 2022-06-19 09:41
Nice, thank you.
