### ISSUE TITLE
Crashes when loading reviews for game that was previously on Steam but no longer is.

### ISSUE THREAD

**Issue by pik4pika** [darklinkpower/PlayniteExtensionsCollection#338] opened 2022-11-21 04:59 UTC
Review Viewer seems to crash when loading Yosuga no Sora. I'm assuming this is because it was previously on Steam so it tries to look for the reviews but they're no longer there. I can't disable this extension for specific games (or at least I don't know how. If you have any idea lmk.)

[Crash log.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10053531/Crash.log.zip)

**Comment by darklinkpower** [comment] 2022-11-21 05:49
Can you share a screenshot of your Links tab of the game in Right click -> Edit please? I think the issue is that one of the game links has an empty url and it was an unforeseen scenario

**Comment by pik4pika** [comment] 2022-11-21 05:52
I had to disable the extension because when I tried to right click it crashes. Here's the image.
![Untitled](https://user-images.githubusercontent.com/116123131/202975341-aade12f3-553f-4c78-9470-0edcc784ad92.png)

**Comment by darklinkpower** [comment] 2022-11-21 05:52
Click the "Links" tab please

**Comment by pik4pika** [comment] 2022-11-21 05:55
![image](https://user-images.githubusercontent.com/116123131/202975749-28144cdd-293e-4fcc-863e-10e2ec57607e.png)

Is it because the links are empty?

**Comment by pik4pika** [comment] 2022-11-21 05:58
Okay, I understand the issue now. I forgot to put a link in. Easily fixable.

**Comment by darklinkpower** [comment] 2022-11-21 06:00
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/3774a8790d40c70b37477d68b21c24dcacc26010 and extension updated with fix.

**Closed by darklinkpower** 2022-11-21 06:00 UTC
