### ISSUE TITLE
[Extra Metadata Loader] Youtube Videos Crashing Playnite to Desktop

### ISSUE THREAD

**Issue by BiggSlime** [darklinkpower/PlayniteExtensionsCollection#524] opened 2024-04-09 03:06 UTC
### Extension name

Extra Metadata Loader

### Bug Description

When searching youtube videos on certain games, the window that pops up will freeze and hard crashes Playnite back to desktop. I noticed that this mostly happens when viewing videos that have age restrictions. 

### To Reproduce

Right click on a game and click on "search video on youtube". Select any video (more likely to occur when selecting an age restricted video). 

### Logs

[extensions.00008.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14912916/extensions.00008.log)
[extensions.00009.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14912917/extensions.00009.log)
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14912918/extensions.log)
[playnite.00000.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14912919/playnite.00000.log)
[playnite.00001.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14912920/playnite.00001.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14912921/playnite.log)

**Comment by darklinkpower** [comment] 2024-04-09 21:26
I can't reproduce it and there isn't any errors in the log. Can you record a video of the issue?

Does this issue always happen in certain games or only sometimes?

**Comment by BiggSlime** [comment] 2024-04-09 22:24
It happens when I click on certain youtube videos. It seems to happen when their is some sort of viewing restriction on the youtube video. 

Here is a recording of what I'm experiencing [https://youtu.be/zDQ0swbJZ9Q](url)

**Comment by BiggSlime** [comment] 2024-04-09 22:52
I also noticed that if I try to open the selected video on after pressing "open on youtube" icon, it will also crash playnite 
Here is a recording of the issue https://youtu.be/gA1gailXYdY

**Comment by darklinkpower** [comment] 2024-04-09 23:22
I've managed to reproduce it. The issue happens not only when pressing the play button, but pressing anything in the page, including like or dislike buttons, etc.


https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/6a2158d8-9c42-40d8-b2b8-5045aa964135

The issue that is causing the crash doesn't happen in the extension but in either Playnite or the web component it uses. Since this can't be fixed on this side, please open an issue in the Playnite repository linking this issue and attach this minimum reproducible example of the issue:

```csharp
using (var webView = PlayniteApi.WebViews.CreateView(1280, 750))
{
    webView.Navigate("https://www.youtube.com/watch?v=dx-oLsap7P0");
    webView.OpenDialog();
}
```

I'm fairly certain this issue didn't happen before before, it's probably caused by either changes in the web component in Playnite or some obscure thing on YouTube.

**Closed by darklinkpower** 2024-04-09 23:22 UTC
Labels: bug, ExtraMetadataLoader
